--
INSERT INTO BANKS (ID, BANK_NAME) VALUES (nextval('bankId_seq'), 'Société Générale');
INSERT INTO BANKS (ID, BANK_NAME) VALUES (nextval('bankId_seq'), 'ING');
--

--
INSERT INTO MONEY_TRANSFER_ORDERS (ID, MONEY_TRANSFER_AMOUNT, MONEY_TRANSFER_ORDER_REF) VALUES (nextval('bankId_seq'), 1000.00,'Tech Repairs');
INSERT INTO MONEY_TRANSFER_ORDERS (ID, MONEY_TRANSFER_AMOUNT, MONEY_TRANSFER_ORDER_REF) VALUES (nextval('bankId_seq'), 800.00,'Taxes and Licences');
INSERT INTO MONEY_TRANSFER_ORDERS (ID, MONEY_TRANSFER_AMOUNT, MONEY_TRANSFER_ORDER_REF) VALUES (nextval('bankId_seq'), 1234.00,'Advertising');
INSERT INTO MONEY_TRANSFER_ORDERS (ID, MONEY_TRANSFER_AMOUNT, MONEY_TRANSFER_ORDER_REF) VALUES (nextval('bankId_seq'), 2000.00,'Meal and Entertainment');
INSERT INTO MONEY_TRANSFER_ORDERS (ID, MONEY_TRANSFER_AMOUNT, MONEY_TRANSFER_ORDER_REF) VALUES (nextval('bankId_seq'), 1500.00,'Other expanses');
--

--
INSERT INTO BANK_ACCOUNTS (ID, ACCOUNT_ID, ACCOUNT_TYPE, SORT_CODE, ACCOUNT_NUMBER, TRANS_CODE, BANK_ID) VALUES (nextval('bankAccountId_seq'), 'SG01', 'CHECKING', '04004', '00050525712', '03000', (select ID from BANKS where BANK_NAME = 'Société Générale'));
INSERT INTO BANK_ACCOUNTS (ID, ACCOUNT_ID, ACCOUNT_TYPE, SORT_CODE, ACCOUNT_NUMBER, TRANS_CODE, BANK_ID) VALUES (nextval('bankAccountId_seq'), 'ING01', 'SAVINGS', '04004', '00050525712', '03000', (select ID from BANKS where BANK_NAME = 'ING'));
--

--
INSERT INTO BANK_ADDRESSES (ID, STREET_NAME, STREET_NUMBER, PO_BOX, CITY_NAME, ZIP_CODE, COUNTRY_NAME, BANK_ID) VALUES (nextval('bankAddressId_seq'), 'av. de Paris', '18', 'Cedex', 'Montmorency', '95800', 'France', (select ID from BANKS where BANK_NAME = 'Société Générale'));
INSERT INTO BANK_ADDRESSES (ID, STREET_NAME, STREET_NUMBER, PO_BOX, CITY_NAME, ZIP_CODE, COUNTRY_NAME, BANK_ID) VALUES (nextval('bankAddressId_seq'), 'blvd. Waterloo', '381', 'INGPOBOX', 'Waterloo', 'B1000', 'Belgium', (select ID from BANKS where BANK_NAME = 'ING'));
--
